import chalk from 'chalk';
import inquirer from 'inquirer';
import fs from 'fs/promises';
import path from 'path';
import { validateOutputPath } from '../utils/path-validation.js';

interface ActionsOptions {
  output?: string;
  schedule?: string;
}

const WORKFLOW_TEMPLATE = `# GitHub Profile README Auto-Update
# Generated by profile-readme-ai
# https://github.com/sena-labs/profile-readme-ai

name: Update Profile README

on:
  # Run on push to main branch
  push:
    branches: [main]
  
  # Run on schedule (default: daily at midnight UTC)
  schedule:
    - cron: '{{SCHEDULE}}'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: \${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install profile-readme-ai
        run: npm install -g profile-readme-ai
      
      - name: Generate README
        env:
          OPENAI_API_KEY: \${{ secrets.OPENAI_API_KEY }}
        run: |
          # Generate new README with AI
          prai generate -u \${{ github.repository_owner }} -t {{THEME}} -o README.md --no-stats
          
          # Or use without AI:
          # prai generate -u \${{ github.repository_owner }} -t {{THEME}} -o README.md --no-ai
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git diff --staged --quiet || git commit -m "🤖 Auto-update profile README"
          git push
`;

const SCHEDULE_OPTIONS = [
  { name: 'Daily at midnight UTC', value: '0 0 * * *' },
  { name: 'Weekly on Sunday', value: '0 0 * * 0' },
  { name: 'Monthly on the 1st', value: '0 0 1 * *' },
  { name: 'Every 6 hours', value: '0 */6 * * *' },
  { name: 'Custom (enter cron expression)', value: 'custom' },
];

const THEME_OPTIONS = [
  'minimal', 'hacker', 'creative', 'corporate', 'retro', 'neon', 'dark', 'light'
];

export async function actions(options: ActionsOptions): Promise<void> {
  console.log(chalk.bold('\n🔧 GitHub Actions Workflow Generator\n'));
  
  // Get schedule
  let schedule = options.schedule;
  if (!schedule) {
    const { scheduleChoice } = await inquirer.prompt([
      {
        type: 'list',
        name: 'scheduleChoice',
        message: 'How often should the README be updated?',
        choices: SCHEDULE_OPTIONS,
      },
    ]);
    
    if (scheduleChoice === 'custom') {
      const { customCron } = await inquirer.prompt([
        {
          type: 'input',
          name: 'customCron',
          message: 'Enter cron expression (e.g., "0 0 * * *"):',
          default: '0 0 * * *',
          validate: (input: string) => {
            const parts = input.trim().split(/\s+/);
            return parts.length === 5 || 'Invalid cron expression (need 5 parts)';
          },
        },
      ]);
      schedule = customCron;
    } else {
      schedule = scheduleChoice;
    }
  }

  // Get theme
  const { theme } = await inquirer.prompt([
    {
      type: 'list',
      name: 'theme',
      message: 'Select theme for auto-generated README:',
      choices: THEME_OPTIONS.map(t => ({ name: t, value: t })),
      default: 'minimal',
    },
  ]);

  // Generate workflow content
  const workflowContent = WORKFLOW_TEMPLATE
    .replace('{{SCHEDULE}}', schedule as string)
    .replace(/{{THEME}}/g, theme);

  // Determine output path
  const outputPath = options.output || '.github/workflows/update-readme.yml';
  const resolvedOutput = validateOutputPath(outputPath, 'yaml');
  const outputDir = path.dirname(resolvedOutput);

  // Preview
  console.log(chalk.bold('\n📄 Workflow Preview:\n'));
  console.log(chalk.gray('─'.repeat(60)));
  console.log(chalk.gray(workflowContent.slice(0, 800) + '...'));
  console.log(chalk.gray('─'.repeat(60)));

  // Confirm save
  const { confirmSave } = await inquirer.prompt([
    {
      type: 'confirm',
      name: 'confirmSave',
      message: `Save workflow to ${outputPath}?`,
      default: true,
    },
  ]);

  if (confirmSave) {
    try {
      // Create directory if it doesn't exist
      await fs.mkdir(outputDir, { recursive: true });
      await fs.writeFile(resolvedOutput, workflowContent, 'utf-8');
      
      console.log(chalk.green(`\n✅ Workflow saved to ${outputPath}`));
      
      console.log(chalk.bold('\n📋 Next Steps:\n'));
      console.log(chalk.cyan('1. Add your OpenAI API key as a repository secret:'));
      console.log(chalk.gray('   Go to: Settings → Secrets → Actions → New repository secret'));
      console.log(chalk.gray('   Name: OPENAI_API_KEY'));
      console.log(chalk.gray('   Value: Your OpenAI API key\n'));
      
      console.log(chalk.cyan('2. Commit and push the workflow:'));
      console.log(chalk.gray(`   git add ${outputPath}`));
      console.log(chalk.gray('   git commit -m "Add auto-update README workflow"'));
      console.log(chalk.gray('   git push\n'));
      
      console.log(chalk.cyan('3. The workflow will run automatically based on your schedule.'));
      console.log(chalk.gray('   You can also trigger it manually from the Actions tab.\n'));
      
      if (theme !== 'minimal') {
        console.log(chalk.yellow(`💡 Tip: Your README will use the "${theme}" theme.`));
        console.log(chalk.gray('   Edit the workflow file to change themes or add more options.\n'));
      }
      
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      const sanitizedMessage = message.replace(/[A-Z]:\\[^\s]+/gi, '[path]').replace(/\/[^\s]+\/[^\s]+/g, '[path]');
      console.error(chalk.red(`\nError saving workflow: ${sanitizedMessage}`));
      process.exit(1);
    }
  } else {
    console.log(chalk.yellow('\nWorkflow not saved.'));
    console.log(chalk.gray('You can copy the preview above and create the file manually.'));
  }
}
